export const authorization = {
  PAGE_ITEM_CATEGORY: "PAGE_ITEM_CATEGORY",
  PAGE_ELEMENT_IMPORT_ITEM_CATEGORY: "PAGE_ELEMENT_IMPORT_ITEM_CATEGORY",
  PAGE_ELEMENT_CREATE_ITEM_CATEGORY: "PAGE_ELEMENT_CREATE_ITEM_CATEGORY",
  PAGE_ELEMENT_EDIT_VIEW_ITEM_CATEGORY: "PAGE_ELEMENT_EDIT_VIEW_ITEM_CATEGORY",
  PAGE_ELEMENT_DISABLE_ITEM_CATEGORY: "PAGE_ELEMENT_DISABLE_ITEM_CATEGORY",

  PAGE_ITEM: "PAGE_ITEM",
  PAGE_ELEMENT_IMPORT_ITEM: "PAGE_ELEMENT_IMPORT_ITEM",
  PAGE_ELEMENT_ADD_ITEM: "PAGE_ELEMENT_ADD_ITEM",
  PAGE_ELEMENT_EDIT_VIEW_ITEM: "PAGE_ELEMENT_EDIT_VIEW_ITEM",
  PAGE_ELEMENT_DISABLE_ITEM: "PAGE_ELEMENT_DISABLE_ITEM",

  PAGE_STOCK: "PAGE_STOCK",
  PAGE_ELEMENT_STOCK_ADD: "PAGE_ELEMENT_STOCK_ADD",
  PAGE_ELEMENT_STOCK_IMPORT: "PAGE_ELEMENT_STOCK_IMPORT",
  PAGE_ELEMENT_STOCK_TRANSFER: "PAGE_ELEMENT_STOCK_TRANSFER",

  PAGE_SALE: "PAGE_SALE",

  PAGE_ELEMENT_ADD_NEW_USER: "PAGE_ELEMENT_ADD_NEW_USER",
  PAGE_ELEMENT_EDIT_VIEW_USER: "PAGE_ELEMENT_EDIT_VIEW_USER",
  PAGE_ELEMENT_RESET_PASSWORD: "PAGE_ELEMENT_RESET_PASSWORD",
  PAGE_ELEMENT_DISABLE_USER: "PAGE_ELEMENT_DISABLE_USER",

  PAGE_ELEMENT_CREATE_NEW_ROLE: "PAGE_ELEMENT_CREATE_NEW_ROLE",
  PAGE_ELEMENT_EDIT_ROLE: "PAGE_ELEMENT_EDIT_ROLE",
  PAGE_ELEMENT_EDIT_VIEW_USER_ROLE: "PAGE_ELEMENT_EDIT_VIEW_USER_ROLE",
  PAGE_ELEMENT_DISABLE_ROLE: "PAGE_ELEMENT_DISABLE_ROLE",

  PAGE_SHOP: "PAGE_SHOP",
  PAGE_ELEMENT_CREATE_SHOP: "PAGE_ELEMENT_CREATE_SHOP",
};

export const transferStatus = {
  inProgress: "IN_PROGRESS"
};

export const ADMIN = 'ADMIN';
export const SELLER = 'SELLER';
export const CASHIER = 'CASHIER';
export const SALE_CONTROLLER = 'SALE_CONTROLLER';